SimpleCrud.Repo.insert!(%SimpleCrud.ExamType{name: "Exam 1"})
SimpleCrud.Repo.insert!(%SimpleCrud.ExamType{name: "Exam 2"})
SimpleCrud.Repo.insert!(%SimpleCrud.ExamType{name: "Exam 3"})
SimpleCrud.Repo.insert!(%SimpleCrud.ExamType{name: "Exam 4"})
SimpleCrud.Repo.insert!(%SimpleCrud.ExamType{name: "Exam 5"})